Support more API endpoints and reorganize measures
Zn4rK/php-withings pull request #27
Opened 2017-09-06 14:29 UTC by Alex131089

* Reorganize measures : put them in Measure object in a Collection
* Remove the specific getters and setters, use generic ones (I don't like to copy/paste code :) ), make properties public
  * Most of the code (if not all) should be retrocompatible.
* Measure objects allows to retrieive their unit, and handle conversion
* Don't overload `Collection::__construct()`, use the new `fromParams()` instead, because overloading prevent the use of `keys()` for example.
  * Limitation (but was already present): added properties become unavailable on `sort()` for example
* Use new endpoint, handle more error code
* Allow users to use the `request` method
* Updated example
* Objects are JsonSerializable (for entities, only `code` is exported), require php>=5.4
* MeasureGroup: use timezone from MeasureGroupCollection

2017-09-06 14:42 UTC, Zn4rK commented
Nice! 

I'll take a look ASAP, but it seems like you've done some extensive work here - awesome!

2017-09-07 15:12 UTC, coral commented
Jebaited

2017-09-07 15:12 UTC, coral commented
🥇

2017-09-07 16:05 UTC, Zn4rK requested changes
Overall, it's a really good and appreciated contribution.
The only strong opinion I have is that we shouldn't use magic overloading if we don't need to, and I like the getters. The strongest reason for it, is that together with PHPDoc it becomes much more easy to work with and it increases the readability when you don't have to figure out what the magic method actually does. 

There's also a few bugs (mainly due to missing $this-> pointers).

We are also missing PHPDoc on a few places, and that needs to be addressed. 

This library follows [PSR-FIG PSR-2](http://www.php-fig.org/psr/psr-2/), and if you can make changes that reflect that I will gladly merge this!

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Api.php
> +    const OLD_ENDPOINT = 'https://wbsapi.withings.net/';
Is there a need for us to keep the old endpoint? Does the new endpoint work with the old calls?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/MeasureCollection.php
> +    public function __get($propertyName)
I'm sceptical to the magic overloading...

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/MeasureCollection.php
> +    public function __call($methodName, $arguments)
Again, sceptical to the magic functions. I get that it's convenient, but for me, it does two things:

1. It decreases the readability of the overall code.
2. It doesn't allow my editor to autocomplete for me.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/ActivityCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/IntradayActivityCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/MeasureGroupCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/SleepCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/SleepStateCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/SubscriptionCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Collection/WorkoutCollection.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Device.php
> +        0  => [
We should be consistent with the way we create arrays. We can use array() or [], but not both. I'm fine with the short tag syntax, but then we'll have to use it all over the project.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Device.php
> +
Missing PHPDOC

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Device.php
> +
Missing PHPDOC

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Device.php
> +    public $name;
Missing PHPDOC, but I'm also hesitant to go with public access on these. I think we are better of with protected properties and getters...

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Device.php
> +        return (isset(self::$modelMap[$modelId]['provideRem']) && self::$modelMap[$modelId]['provideRem']);
Where does $modelId come from here? Are we missing a $this pointer?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +    public $code;
Again, public access instead of protected.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +    public function __call($methodName, $arguments)
As I stated earlier, I don't like the magic overloading. I think getters are more readable.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +        return floatval(round($this->value, 2)).' '.((!empty($this->unit)) ? $this->unit : '');
Clever!

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +        if ($converted->isImperial)
Where does $converted come from here?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/MeasureAttrib.php
> +        0 => [
This also need to be consistent with the previous comment I had about arrays.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/MeasureAttrib.php
> +    public $id;
Should be protected access and accessed with getters for readability... I also would like some PHPDoc, on this.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/MeasureGroupCategory.php
> +    public $id;
Same as before. I prefer protected access with getters for readability.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +        if (isset($this->code))
To keep up with PSR-FIG (PSR-2) we should encapsulate the if statements so we don't run in to [#gotofail](https://nakedsecurity.sophos.com/2014/02/24/anatomy-of-a-goto-fail-apples-ssl-bug-explained-plus-an-unofficial-patch/)

More on [PSR-FIG PSR-2 here](http://www.php-fig.org/psr/psr-2/)

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Measure.php
> +            foreach ($this->extra as $key => $extra)
The same goes for the foreach. Missing curly braces that ends it...

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Activity.php
> +        //$instance->raw = $params;
junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/IntradayActivity.php
> +        //$instance->raw = $params;
junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/MeasureGroup.php
> +    public $groupId;
The access should not be public.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/MeasureGroup.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Sleep.php
> +    public $createdAt; // activityDate
Public access and missing getters.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Sleep.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Workout.php
> +    public $startDate;
Public access and missing getters.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Traits/JsonUtils.php
> +        foreach ($properties as $property)
Again, we should follow PSR-FIG PSR-2 regarding curly braces.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Subscription.php
> +        return $this->jsonSerializeProperties(array_keys(get_object_vars($this)));
This is inconsistent to your previous use: https://github.com/Zn4rK/php-withings/pull/27/files#diff-7f5014e5a49614cb4b6afe2835695e4aR87. 

This way looks better, but does it make a difference? If not, we should try to be consistent.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/User.php
> +        $this_properties = array_keys(get_object_vars($this));
Also inconsistent to your previous use: https://github.com/Zn4rK/php-withings/pull/27/files#diff-7f5014e5a49614cb4b6afe2835695e4aR87.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/WorkoutCategory.php
> +    public $id;
Public access instead of protected with getters.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/MeasureGroup.php
> +    public $createdAt;
Public access instead of protected with getters.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Workout.php
> +    public static $measuresMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Sleep.php
> +    public static $measuresMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/MeasureGroup.php
> +    public static $measuresMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/IntradayActivity.php
> +    public static $measuresMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/IntradayActivity.php
> +    public $createdAt; // activityDate
Public access instead of protected with getters..

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Activity.php
> +    public static $measuresMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Activity.php
> +    public $createdAt;
Public access instead of protected with getters.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/Entity/WorkoutCategory.php
> +    public static $categoriesMap = array(
Same comment about arrays as previously.

2017-09-07 16:05 UTC, Zn4rK commented on src/Paxx/Withings/MeasureCollection/Workout.php
> +        //$instance->raw = $params;
Junk?

2017-09-07 16:09 UTC, Alex131089 commented on src/Paxx/Withings/Entity/Device.php
> +        return (isset(self::$modelMap[$modelId]['provideRem']) && self::$modelMap[$modelId]['provideRem']);
Yep !

2017-09-07 16:11 UTC, Alex131089 commented on src/Paxx/Withings/Entity/Measure.php
> +        if ($converted->isImperial)
Should be `$this` of course.

2017-09-07 16:19 UTC, Alex131089 commented on src/Paxx/Withings/Entity/Subscription.php
> +        return $this->jsonSerializeProperties(array_keys(get_object_vars($this)));
Subscription : properties are protected, we need to look for properties inside the class
MeasureCollection : properties are public, we only want to serialize public properties so use call_user_func

2017-09-07 16:19 UTC, Alex131089 commented on src/Paxx/Withings/Entity/User.php
> +        $this_properties = array_keys(get_object_vars($this));
See https://github.com/Zn4rK/php-withings/pull/27#discussion_r137587063

2017-09-07 16:20 UTC, Zn4rK commented on src/Paxx/Withings/Entity/Subscription.php
> +        return $this->jsonSerializeProperties(array_keys(get_object_vars($this)));
Gotcha 👍

2017-09-07 16:26 UTC, Alex131089 commented on src/Paxx/Withings/Api.php
> +    const OLD_ENDPOINT = 'https://wbsapi.withings.net/';
I read somewhere the user "endpoint" is only available on the old one, but that doesn't seems to be true. That's "in case of".

2017-09-07 16:27 UTC, Alex131089 commented on src/Paxx/Withings/Collection/MeasureCollection.php
> +    public function __call($methodName, $arguments)
That's why I put properties as public, see the coming comment below.

2017-09-07 16:35 UTC, Alex131089 commented
> The only strong opinion I have is that we shouldn't use magic overloading if we don't need to, and I like the getters. The strongest reason for it, is that together with PHPDoc it becomes much more easy to work with and it increases the readability when you don't have to figure out what the magic method actually does.

I understand that. However, my "IDE" is Codiad, so I don't have autocompletion/whateverItIs to create the getters. I'm not going to create them by hand.
The __get() and __call() I put are mostly for retrocompatibility, IMO, properties should be public (is there a reason to prevent "users" (developers) to access them ?), documented, and used directly.

> We are also missing PHPDoc one a few places, and that needs to be addressed.

Yes, it's needed.

> This library follows PSR-FIG PSR-2, and if you can make changes that reflect that I will gladly merge this!

Is there something else than what you mentionned that should be changed for compliance ?

* About the arrays, maybe an IDE can handle this ?
* raw debug junk : maybe this could be placed under a debug tag / constant ?
* missing braces: I was lazy, I may add them one day
* missing doc : same (they're pretty obvious though)

Btw, what is the "Jebaited" thing ?

2017-09-07 16:39 UTC, Zn4rK commented
I have no idea about the jebaited thing. A friend tried to be funny. Sorry about that.

2017-09-07 16:45 UTC, coral commented
Jebaited

2017-09-07 16:47 UTC, Zn4rK commented
Normally, I wouldn't directly disagree with you. I would probably set them at protected and have the developer extend and replace the class if needed anyway though. With the dependency injection in Laravel it's possible.

But since our data is coming from an external API we need to be sure that it hasn't changed by some third party library or that another developer in our project has taken a shortcut or made a logic error, or something else. With non-public properties and getters we can be sure that nothing has happened to our data.

Other than that, it's just a preference.

2017-09-07 16:48 UTC, Zn4rK commented
How about this? I'll merge this into development, and I'll try to go over the code and add the getters...

2017-09-07 16:52 UTC, Zn4rK commented
I like the debug constant idea!

2017-09-20 17:27 UTC, Alex131089 commented
Fixed the variable errors & the noted braces.
Array notation, visibility and getters are left to you.
The project I worked on planned to use this lib, but the project is no longer alive :/
I hope the changes will be useful to someone else though !

2017-09-25 01:12 UTC, merged

2017-09-25 01:14 UTC, Zn4rK commented
Thank you for this! And I'm sorry to hear about your project...
Merging it into development to give me time to adjust the code to my likings :)